name: Production Workflow
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Логин на DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_BOT_KEY }}
      - name: Билд и Пуш Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/vpn-bot:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/vpn-bot:latest
      - name: Деплой
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}         
          username: ${{ secrets.SERVER_USER }}    
          key: ${{ secrets.SERVER_SSH_KEY }}     
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/vpn-bot:latest
            cd /root/Vpn_bot
            echo "${{ secrets.BOT_ENV_PROD }}" > .env
            docker-compose down
            docker-compose up -d
            docker system prune -f

  
